# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exile.Menu')),
            ],
            options={
                'verbose_name': 'Menu principal',
                'verbose_name_plural': 'Menu principal',
            },
        ),
        migrations.CreateModel(
            name='OrdenPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Orden de la pagina',
                'verbose_name_plural': 'Orden de las paginas',
            },
        ),
        migrations.CreateModel(
            name='OrdenSeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile.Menu')),
            ],
            options={
                'verbose_name': 'Orden de secci\xf3n',
                'verbose_name_plural': 'Orden de secciones',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('contenido', redactor.fields.RedactorField(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exile.Page')),
            ],
            options={
                'verbose_name': 'Secci\xf3n',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.AddField(
            model_name='ordenseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile.Seccion'),
        ),
        migrations.AddField(
            model_name='ordenpagina',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile.Page'),
        ),
        migrations.AddField(
            model_name='ordenpagina',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exile.Seccion'),
        ),
    ]
