# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exile', '0002_auto_20160914_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitem',
            name='seccion',
        ),
        migrations.AddField(
            model_name='ordensubitem',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exile.ItemSeccion'),
        ),
    ]
