# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exile', '0004_paginaprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginaprincipal',
            name='pagina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exile.Page'),
        ),
    ]
