# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exile', '0007_auto_20170511_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
